### ISSUE TITLE
/dbping endpoint return strange values

### ISSUE THREAD

**Issue by Antse** [neocase/docker-go-starter-kit#2]
/dbping should test the db status but when we are reaching the endpoint the result is : 

hotstName : 54c8fad0618f
DbStatus : pq: SSL is not enabled on the server
hotstName : 54c8fad0618f
DbStatus :db good

Only one block should be writen in the response writer.

**Comment by sbouaked** [comment]
fixed (error in if/else statement). and add `sslmode=disable` in the the query string
